version: '3'

services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    expose:
      - 5000
    environment:
      VIRTUAL_HOST: DOMAIN.TLD
      LETSENCRYPT_HOST: DOMAIN.TLD
      LETSENCRYPT_EMAIL: docker@DOMAIN.TLD
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - data:/data
      - ./auth:/auth
    restart: always

volumes:
  data:

networks:
  default:
    external:
      name: nginx-proxy
