version: '3.7'

services:

  git-server-hooks:
    image: PRIV_REG_SERVER/gbili/git-server-hooks:0.1.1
    container_name: git-server-hooks
    environment:
      GIT_REPOS_OWNERNAME: REPO_USERNAME
      VIRTUAL_HOST: DOMAIN.TLD
      LETSENCRYPT_HOST: DOMAIN.TLD
      LETSENCRYPT_EMAIL: mail@DOMAIN.TLD
    ports:
      - "2222:22"
    volumes:
      - ssh-keys:/u/keys
      - git-repos:/u/gbili
      - node-apps:/node-server/gbili
    restart: always

volumes:
  ssh-keys:
  git-repos:
  node-apps:

networks:
  default:
    external:
      name: nginx-proxy
