version: '3.7'

services:
  git-server-hooks-repo-add-service:
    image: PRIV_REG_SERVER/gbili/git-server-hooks-repo-add:0.2.0
    environment:
      GIT_REPO_NAME: GIT_REPO_DIRNAME
      GIT_REPO_OWNERNAME: gbili
      GIT_HOOKS_NAMESPACE: GIT_HOOK_NS
    volumes:
      - git-repos:/u/gbili
      - node-apps:/node-server/gbili
    restart: "no"

volumes:
  git-repos:
    external:
      name: git-server-hooks_git-repos
  node-apps:
    external:
      name: git-server-hooks_node-apps
